### ISSUE TITLE
POST body parameters

### ISSUE THREAD

**Issue by litzbalane2017** [gabrielginter/flutter-upchunk#1]
Good Day.

Thank you for this plugin. Any chance we can set body parameters on the POST request?

**Comment by gabrielginter** [comment]
Hi @litzbalane2017 can you give me more information about your use case? Perhaps there is other way to solve your problem.

At the moment the plugin sends a PUT request with a raw `Stream<List<int>>` as the body with no parameters whatsoever and content type set to the mime type of the file provided in the options.

If you wish to send parameters in the body, the content type would have to be set as a multipart form which would defeat the purpose of this plugin I believe, if you have an idea for an approach, do share.

**Comment by litzbalane2017** [comment]
I see. I was thinking of replacing multipart form using this plugin, by attaching data body parameters in the POST request. Currently, flutter has very few working POST uploads with upload progress listeners.

**Comment by gabrielginter** [comment]
Have you taken a look at [dio Plugin](https://pub.dev/packages/dio), this package will give you a lot more options and callbacks, feel free to repurpose some of the up_chunk code to create a helper class to do this.

I will consider adding this functionality to this plugin to make things easier for your type of use case.

**Comment by litzbalane2017** [comment]
Yes, I've seen it. DIO is  too much for my use case. I might use two POST requests for the moment. Thank you!
