### ISSUE TITLE
How to cancel uploading?

### ISSUE THREAD

**Issue by KOSNOWMAN** [gabrielginter/flutter-upchunk#2]
There are some methods,  pause, resume, restart.
I can't find method to cancel upload.
How to cancel upload progress?

**Comment by gabrielginter** [comment]
Hi @KOSNOWMAN 

You raised a fair point, at the moment there is no method to cancel the upload abruptly, you can only use `pause()` but this would still try to finish uploading the current chunk.

I will add a method that allows this functionality in the upcoming days.

**Comment by gabrielginter** [comment]
version 1.1.0 published with support to cancel uploads abruptly, see method `stop`
