### ISSUE TITLE
Add the option to start the upload at a certain chunk

### ISSUE THREAD

**Issue by NazarenoCavazzon** [gabrielginter/flutter-upchunk#4]
We are trying to implement upload persistence, and for that we wanted to save the last successful chunk uploaded, so if somethings fails we start from that specific chunk.

**Comment by gabrielginter** [comment]
hola @NazarenoCavazzon thanks for the feature request, after skimming through the pull request I see no apparent issues, I'll review it and test it as soon as I have some time. Have you tested this code yourself already?

**Comment by NazarenoCavazzon** [comment]
I tried with the backend we have at work, but we had some problems with our backend, hopefully I can fix the backend and make it work.

**Comment by gabrielginter** [comment]
Hi @NazarenoCavazzon I'm so sorry for the delay on this, I'm sure you already found a solution, nevertheless check out his last version that contains this feature. The new package was refactored to simplify it and support Flutter Web.
